// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    return window.decache = function(uri, stamp) {
      var seperator;

      if (!stamp) {
        stamp = new Date().getTime();
      }
      seperator = uri.indexOf('?') > -1 ? '&' : '?';
      return uri.concat(seperator, stamp);
    };
  })();

}).call(this);
