// Generated by CoffeeScript 1.4.0
(function() {

  (function() {
    var decache;
    decache = function(uri, stamp) {
      var seperator;
      if (!stamp) {
        stamp = new Date().getTime();
      }
      seperator = uri.indexOf('?') > -1 ? '&' : '?';
      return uri.concat(seperator, stamp);
    };
    if (typeof module !== "undefined" && module !== null) {
      module.exports = decache;
    }
    if (typeof window !== "undefined" && window !== null) {
      window.decache = decache;
    }
    if (typeof define === 'function' && define.amd && typeof define.amd === 'object') {
      return define('decache', [], function() {
        return decache;
      });
    }
  })();

}).call(this);
